### ISSUE TITLE
output of funs returning watershed

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwatlasbc#11]
this is output from API (fwa_watershed_at_measure)
<img width="696" alt="Screen Shot 2020-11-03 at 4 18 43 PM" src="https://user-images.githubusercontent.com/15878432/98054639-5926be80-1df0-11eb-9641-3fb47a596105.png">

Which columns should we keep or add?

For `point_to` and `xy_to` we could add: distance_to_stream (i.e. how far was point to nearest), blue_line_key, downstream_route_measure (or rename to distance_upstream)

for `blue_line_key_to` we could add: blue_line_key and downstream_route_measure (or rename to distance_upstream)

**Comment by joethorley** [comment]
Good questions - if possible for consistency I think we should have the same columns in each one ie distance_to_stream (0 for `blue_line_key_to`), blue_line_key and distance_upstream

**Comment by joethorley** [comment]
On reflection I don't think there is any point returning blue_line_key because although a point may be closer as the bird flies to a blue line key it may be closer as the water flows to another one. Also the point of the function is just to get a polygon so I don't think this other information should be given to the user.

**Comment by sebdalgarno** [comment]
OK good points...so for simplicit it will be a sf object with geometry and no attributes (columns)

This is the function used to find the nearest stream: https://www.hillcrestgeo.ca/fwapg/functions/fwa_indexpoint.html
I'm assuming it takes into account whether the point is actually in the watershed (i.e. not just closest as the bird flies) although it this is not explicit in the description

**Comment by joethorley** [comment]
Ahh - good point - if it is as the water flows then it probably makes sense to have the blue line key, distance to stream and distance upstream - otherwise not.

**Comment by sebdalgarno** [comment]
if it is finding as crow flies is that undesirable behaviour? or are we ok with either scenario?

**Comment by joethorley** [comment]
No if as crow flies it could be totally misleading because the nearest blue line key could be outside the watershed.

In fact thinking about it some more if the point is higher than all blue line keys it won't include any and so its misleading to link to any - consider the point at the exact top of a mountain. it a sense water could flow in any direction to all the surrounding blue line keys. I renege and think we should just return the watershed polygon.

**Comment by joethorley** [comment]
Having slept on it I still think the watershed based on a point should only return the polygon but one based on a blue line key should include the blue line key and distance_upstream (distance_from_mouth?)

**Comment by sebdalgarno** [comment]
Sounds good. I will change distance_upstream arg name to distance_from_mouth as I think it is more clear. 
I've opened a separate issue (#12)  for the fwa_indexpoint function (and how it finds nearest stream).
